// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/core/interfaces/secondary/auth.go
//
// Generated by this command:
//
//	mockgen -source=./src/core/interfaces/secondary/auth.go -destination=./src/core/services/mocks/auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	account "eletronic_point/src/core/domain/account"
	credentials "eletronic_point/src/core/domain/credentials"
	errors "eletronic_point/src/core/domain/errors"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthPort is a mock of AuthPort interface.
type MockAuthPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthPortMockRecorder
	isgomock struct{}
}

// MockAuthPortMockRecorder is the mock recorder for MockAuthPort.
type MockAuthPortMockRecorder struct {
	mock *MockAuthPort
}

// NewMockAuthPort creates a new mock instance.
func NewMockAuthPort(ctrl *gomock.Controller) *MockAuthPort {
	mock := &MockAuthPort{ctrl: ctrl}
	mock.recorder = &MockAuthPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthPort) EXPECT() *MockAuthPortMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthPort) Login(arg0 credentials.Credentials) (account.Account, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0)
	ret0, _ := ret[0].(account.Account)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthPortMockRecorder) Login(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthPort)(nil).Login), arg0)
}

// ResetAccountPassword mocks base method.
func (m *MockAuthPort) ResetAccountPassword(accountID *uuid.UUID, newPassword string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAccountPassword", accountID, newPassword)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// ResetAccountPassword indicates an expected call of ResetAccountPassword.
func (mr *MockAuthPortMockRecorder) ResetAccountPassword(accountID, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAccountPassword", reflect.TypeOf((*MockAuthPort)(nil).ResetAccountPassword), accountID, newPassword)
}
