// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/core/interfaces/secondary/course.go
//
// Generated by this command:
//
//	mockgen -source=./src/core/interfaces/secondary/course.go -destination=./src/core/services/mocks/course.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	course "eletronic_point/src/core/domain/course"
	errors "eletronic_point/src/core/domain/errors"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCoursePort is a mock of CoursePort interface.
type MockCoursePort struct {
	ctrl     *gomock.Controller
	recorder *MockCoursePortMockRecorder
	isgomock struct{}
}

// MockCoursePortMockRecorder is the mock recorder for MockCoursePort.
type MockCoursePortMockRecorder struct {
	mock *MockCoursePort
}

// NewMockCoursePort creates a new mock instance.
func NewMockCoursePort(ctrl *gomock.Controller) *MockCoursePort {
	mock := &MockCoursePort{ctrl: ctrl}
	mock.recorder = &MockCoursePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoursePort) EXPECT() *MockCoursePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCoursePort) Create(data course.Course) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCoursePortMockRecorder) Create(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCoursePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockCoursePort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCoursePortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCoursePort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockCoursePort) Get(id uuid.UUID) (course.Course, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(course.Course)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCoursePortMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCoursePort)(nil).Get), id)
}

// List mocks base method.
func (m *MockCoursePort) List(_filters filters.CourseFilters) ([]course.Course, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]course.Course)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCoursePortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCoursePort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockCoursePort) Update(data course.Course) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", data)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCoursePortMockRecorder) Update(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCoursePort)(nil).Update), data)
}
