// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/secondary/file.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/secondary/file.go -destination=src/core/services/mocks/file.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFilePort is a mock of FilePort interface.
type MockFilePort struct {
	ctrl     *gomock.Controller
	recorder *MockFilePortMockRecorder
	isgomock struct{}
}

// MockFilePortMockRecorder is the mock recorder for MockFilePort.
type MockFilePortMockRecorder struct {
	mock *MockFilePort
}

// NewMockFilePort creates a new mock instance.
func NewMockFilePort(ctrl *gomock.Controller) *MockFilePort {
	mock := &MockFilePort{ctrl: ctrl}
	mock.recorder = &MockFilePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilePort) EXPECT() *MockFilePortMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFilePort) Get(name string) (*os.File, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFilePortMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFilePort)(nil).Get), name)
}
