// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/secondary/institution.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/secondary/institution.go -destination=src/core/services/mocks/institution.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	institution "eletronic_point/src/core/domain/institution"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInstitutionPort is a mock of InstitutionPort interface.
type MockInstitutionPort struct {
	ctrl     *gomock.Controller
	recorder *MockInstitutionPortMockRecorder
	isgomock struct{}
}

// MockInstitutionPortMockRecorder is the mock recorder for MockInstitutionPort.
type MockInstitutionPortMockRecorder struct {
	mock *MockInstitutionPort
}

// NewMockInstitutionPort creates a new mock instance.
func NewMockInstitutionPort(ctrl *gomock.Controller) *MockInstitutionPort {
	mock := &MockInstitutionPort{ctrl: ctrl}
	mock.recorder = &MockInstitutionPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstitutionPort) EXPECT() *MockInstitutionPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstitutionPort) Create(data institution.Institution) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInstitutionPortMockRecorder) Create(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstitutionPort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockInstitutionPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstitutionPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstitutionPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockInstitutionPort) Get(id uuid.UUID) (institution.Institution, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(institution.Institution)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInstitutionPortMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInstitutionPort)(nil).Get), id)
}

// List mocks base method.
func (m *MockInstitutionPort) List(_filters filters.InstitutionFilters) ([]institution.Institution, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]institution.Institution)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInstitutionPortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInstitutionPort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockInstitutionPort) Update(data institution.Institution) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", data)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInstitutionPortMockRecorder) Update(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInstitutionPort)(nil).Update), data)
}
