// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/core/interfaces/secondary/passwordReset.go
//
// Generated by this command:
//
//	mockgen -source=./src/core/interfaces/secondary/passwordReset.go -destination=./src/core/services/mocks/passwordReset.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetPort is a mock of PasswordResetPort interface.
type MockPasswordResetPort struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetPortMockRecorder
	isgomock struct{}
}

// MockPasswordResetPortMockRecorder is the mock recorder for MockPasswordResetPort.
type MockPasswordResetPortMockRecorder struct {
	mock *MockPasswordResetPort
}

// NewMockPasswordResetPort creates a new mock instance.
func NewMockPasswordResetPort(ctrl *gomock.Controller) *MockPasswordResetPort {
	mock := &MockPasswordResetPort{ctrl: ctrl}
	mock.recorder = &MockPasswordResetPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetPort) EXPECT() *MockPasswordResetPortMockRecorder {
	return m.recorder
}

// AskPasswordResetMail mocks base method.
func (m *MockPasswordResetPort) AskPasswordResetMail(email string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskPasswordResetMail", email)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// AskPasswordResetMail indicates an expected call of AskPasswordResetMail.
func (mr *MockPasswordResetPortMockRecorder) AskPasswordResetMail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskPasswordResetMail", reflect.TypeOf((*MockPasswordResetPort)(nil).AskPasswordResetMail), email)
}

// DeleteResetPasswordEntry mocks base method.
func (m *MockPasswordResetPort) DeleteResetPasswordEntry(token string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResetPasswordEntry", token)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// DeleteResetPasswordEntry indicates an expected call of DeleteResetPasswordEntry.
func (mr *MockPasswordResetPortMockRecorder) DeleteResetPasswordEntry(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResetPasswordEntry", reflect.TypeOf((*MockPasswordResetPort)(nil).DeleteResetPasswordEntry), token)
}

// FindPasswordResetByToken mocks base method.
func (m *MockPasswordResetPort) FindPasswordResetByToken(token string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPasswordResetByToken", token)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// FindPasswordResetByToken indicates an expected call of FindPasswordResetByToken.
func (mr *MockPasswordResetPortMockRecorder) FindPasswordResetByToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPasswordResetByToken", reflect.TypeOf((*MockPasswordResetPort)(nil).FindPasswordResetByToken), token)
}

// GetAccountIDByResetPasswordToken mocks base method.
func (m *MockPasswordResetPort) GetAccountIDByResetPasswordToken(token string) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIDByResetPasswordToken", token)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetAccountIDByResetPasswordToken indicates an expected call of GetAccountIDByResetPasswordToken.
func (mr *MockPasswordResetPortMockRecorder) GetAccountIDByResetPasswordToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIDByResetPasswordToken", reflect.TypeOf((*MockPasswordResetPort)(nil).GetAccountIDByResetPasswordToken), token)
}
