// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/secondary/session.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/secondary/session.go -destination=src/core/services/mocks/session.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	authorization "eletronic_point/src/core/domain/authorization"
	errors "eletronic_point/src/core/domain/errors"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionPort is a mock of SessionPort interface.
type MockSessionPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionPortMockRecorder
	isgomock struct{}
}

// MockSessionPortMockRecorder is the mock recorder for MockSessionPort.
type MockSessionPortMockRecorder struct {
	mock *MockSessionPort
}

// NewMockSessionPort creates a new mock instance.
func NewMockSessionPort(ctrl *gomock.Controller) *MockSessionPort {
	mock := &MockSessionPort{ctrl: ctrl}
	mock.recorder = &MockSessionPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionPort) EXPECT() *MockSessionPortMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockSessionPort) Exists(uID *uuid.UUID, token string) (bool, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", uID, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSessionPortMockRecorder) Exists(uID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSessionPort)(nil).Exists), uID, token)
}

// GetSessionByAccountID mocks base method.
func (m *MockSessionPort) GetSessionByAccountID(uID *uuid.UUID) (authorization.Authorization, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByAccountID", uID)
	ret0, _ := ret[0].(authorization.Authorization)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetSessionByAccountID indicates an expected call of GetSessionByAccountID.
func (mr *MockSessionPortMockRecorder) GetSessionByAccountID(uID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByAccountID", reflect.TypeOf((*MockSessionPort)(nil).GetSessionByAccountID), uID)
}

// RemoveSession mocks base method.
func (m *MockSessionPort) RemoveSession(uID *uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSession", uID)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockSessionPortMockRecorder) RemoveSession(uID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockSessionPort)(nil).RemoveSession), uID)
}

// Store mocks base method.
func (m *MockSessionPort) Store(uID *uuid.UUID, accessToken string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", uID, accessToken)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockSessionPortMockRecorder) Store(uID, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockSessionPort)(nil).Store), uID, accessToken)
}
