// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/core/interfaces/secondary/student.go
//
// Generated by this command:
//
//	mockgen -source=./src/core/interfaces/secondary/student.go -destination=./src/core/services/mocks/student.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	student "eletronic_point/src/core/domain/student"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentPort is a mock of StudentPort interface.
type MockStudentPort struct {
	ctrl     *gomock.Controller
	recorder *MockStudentPortMockRecorder
	isgomock struct{}
}

// MockStudentPortMockRecorder is the mock recorder for MockStudentPort.
type MockStudentPortMockRecorder struct {
	mock *MockStudentPort
}

// NewMockStudentPort creates a new mock instance.
func NewMockStudentPort(ctrl *gomock.Controller) *MockStudentPort {
	mock := &MockStudentPort{ctrl: ctrl}
	mock.recorder = &MockStudentPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentPort) EXPECT() *MockStudentPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStudentPort) Create(arg0 student.Student) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStudentPortMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentPort)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockStudentPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStudentPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStudentPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockStudentPort) Get(id uuid.UUID, _filters filters.StudentFilters) (student.Student, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id, _filters)
	ret0, _ := ret[0].(student.Student)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStudentPortMockRecorder) Get(id, _filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStudentPort)(nil).Get), id, _filters)
}

// List mocks base method.
func (m *MockStudentPort) List(_filters filters.StudentFilters) ([]student.Student, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]student.Student)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStudentPortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStudentPort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockStudentPort) Update(arg0 student.Student) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudentPortMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudentPort)(nil).Update), arg0)
}
