// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/core/interfaces/secondary/timeRecordStatus.go
//
// Generated by this command:
//
//	mockgen -source=./src/core/interfaces/secondary/timeRecordStatus.go -destination=./src/core/services/mocks/timeRecordStatus.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	timeRecordStatus "eletronic_point/src/core/domain/timeRecordStatus"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTimeRecordStatusPort is a mock of TimeRecordStatusPort interface.
type MockTimeRecordStatusPort struct {
	ctrl     *gomock.Controller
	recorder *MockTimeRecordStatusPortMockRecorder
	isgomock struct{}
}

// MockTimeRecordStatusPortMockRecorder is the mock recorder for MockTimeRecordStatusPort.
type MockTimeRecordStatusPortMockRecorder struct {
	mock *MockTimeRecordStatusPort
}

// NewMockTimeRecordStatusPort creates a new mock instance.
func NewMockTimeRecordStatusPort(ctrl *gomock.Controller) *MockTimeRecordStatusPort {
	mock := &MockTimeRecordStatusPort{ctrl: ctrl}
	mock.recorder = &MockTimeRecordStatusPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeRecordStatusPort) EXPECT() *MockTimeRecordStatusPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTimeRecordStatusPort) Create(data timeRecordStatus.TimeRecordStatus) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTimeRecordStatusPortMockRecorder) Create(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTimeRecordStatusPort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockTimeRecordStatusPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTimeRecordStatusPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTimeRecordStatusPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockTimeRecordStatusPort) Get(id uuid.UUID) (timeRecordStatus.TimeRecordStatus, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(timeRecordStatus.TimeRecordStatus)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTimeRecordStatusPortMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTimeRecordStatusPort)(nil).Get), id)
}

// List mocks base method.
func (m *MockTimeRecordStatusPort) List() ([]timeRecordStatus.TimeRecordStatus, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]timeRecordStatus.TimeRecordStatus)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTimeRecordStatusPortMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTimeRecordStatusPort)(nil).List))
}

// Update mocks base method.
func (m *MockTimeRecordStatusPort) Update(data timeRecordStatus.TimeRecordStatus) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", data)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTimeRecordStatusPortMockRecorder) Update(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTimeRecordStatusPort)(nil).Update), data)
}
