// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/core/interfaces/secondary/timeRecord.go
//
// Generated by this command:
//
//	mockgen -source=./src/core/interfaces/secondary/timeRecord.go -destination=./src/core/services/mocks/timeRecord.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	timeRecord "eletronic_point/src/core/domain/timeRecord"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTimeRecordPort is a mock of TimeRecordPort interface.
type MockTimeRecordPort struct {
	ctrl     *gomock.Controller
	recorder *MockTimeRecordPortMockRecorder
	isgomock struct{}
}

// MockTimeRecordPortMockRecorder is the mock recorder for MockTimeRecordPort.
type MockTimeRecordPortMockRecorder struct {
	mock *MockTimeRecordPort
}

// NewMockTimeRecordPort creates a new mock instance.
func NewMockTimeRecordPort(ctrl *gomock.Controller) *MockTimeRecordPort {
	mock := &MockTimeRecordPort{ctrl: ctrl}
	mock.recorder = &MockTimeRecordPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeRecordPort) EXPECT() *MockTimeRecordPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTimeRecordPort) Create(arg0 timeRecord.TimeRecord) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTimeRecordPortMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTimeRecordPort)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockTimeRecordPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTimeRecordPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTimeRecordPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockTimeRecordPort) Get(id uuid.UUID, _filters filters.TimeRecordFilters) (timeRecord.TimeRecord, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id, _filters)
	ret0, _ := ret[0].(timeRecord.TimeRecord)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTimeRecordPortMockRecorder) Get(id, _filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTimeRecordPort)(nil).Get), id, _filters)
}

// List mocks base method.
func (m *MockTimeRecordPort) List(_filters filters.TimeRecordFilters) ([]timeRecord.TimeRecord, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]timeRecord.TimeRecord)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTimeRecordPortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTimeRecordPort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockTimeRecordPort) Update(arg0 timeRecord.TimeRecord) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTimeRecordPortMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTimeRecordPort)(nil).Update), arg0)
}

// UpdateStatus mocks base method.
func (m *MockTimeRecordPort) UpdateStatus(timeRecordID, updatedBy, statusID uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", timeRecordID, updatedBy, statusID)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTimeRecordPortMockRecorder) UpdateStatus(timeRecordID, updatedBy, statusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTimeRecordPort)(nil).UpdateStatus), timeRecordID, updatedBy, statusID)
}
