// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/primary/account.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/primary/account.go -destination=src/apps/api/handlers/mocks/account.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	account "eletronic_point/src/core/domain/account"
	errors "eletronic_point/src/core/domain/errors"
	person "eletronic_point/src/core/domain/person"
	updatePassword "eletronic_point/src/core/domain/updatePassword"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountPort is a mock of AccountPort interface.
type MockAccountPort struct {
	ctrl     *gomock.Controller
	recorder *MockAccountPortMockRecorder
	isgomock struct{}
}

// MockAccountPortMockRecorder is the mock recorder for MockAccountPort.
type MockAccountPortMockRecorder struct {
	mock *MockAccountPort
}

// NewMockAccountPort creates a new mock instance.
func NewMockAccountPort(ctrl *gomock.Controller) *MockAccountPort {
	mock := &MockAccountPort{ctrl: ctrl}
	mock.recorder = &MockAccountPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountPort) EXPECT() *MockAccountPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountPort) Create(arg0 account.Account) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountPortMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountPort)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockAccountPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountPort)(nil).Delete), id)
}

// FindByID mocks base method.
func (m *MockAccountPort) FindByID(uID *uuid.UUID) (account.Account, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", uID)
	ret0, _ := ret[0].(account.Account)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountPortMockRecorder) FindByID(uID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountPort)(nil).FindByID), uID)
}

// List mocks base method.
func (m *MockAccountPort) List(arg0 filters.AccountFilters) ([]account.Account, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]account.Account)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccountPortMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccountPort)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockAccountPort) Update(arg0 account.Account) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountPortMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountPort)(nil).Update), arg0)
}

// UpdateAccountPassword mocks base method.
func (m *MockAccountPort) UpdateAccountPassword(accountID *uuid.UUID, data updatePassword.UpdatePassword) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountPassword", accountID, data)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// UpdateAccountPassword indicates an expected call of UpdateAccountPassword.
func (mr *MockAccountPortMockRecorder) UpdateAccountPassword(accountID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountPassword", reflect.TypeOf((*MockAccountPort)(nil).UpdateAccountPassword), accountID, data)
}

// UpdateAccountProfile mocks base method.
func (m *MockAccountPort) UpdateAccountProfile(arg0 person.Person) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountProfile", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// UpdateAccountProfile indicates an expected call of UpdateAccountProfile.
func (mr *MockAccountPortMockRecorder) UpdateAccountProfile(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountProfile", reflect.TypeOf((*MockAccountPort)(nil).UpdateAccountProfile), arg0)
}
