// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/primary/auth.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/primary/auth.go -destination=src/apps/api/handlers/mocks/auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	authorization "eletronic_point/src/core/domain/authorization"
	credentials "eletronic_point/src/core/domain/credentials"
	errors "eletronic_point/src/core/domain/errors"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthPort is a mock of AuthPort interface.
type MockAuthPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthPortMockRecorder
	isgomock struct{}
}

// MockAuthPortMockRecorder is the mock recorder for MockAuthPort.
type MockAuthPortMockRecorder struct {
	mock *MockAuthPort
}

// NewMockAuthPort creates a new mock instance.
func NewMockAuthPort(ctrl *gomock.Controller) *MockAuthPort {
	mock := &MockAuthPort{ctrl: ctrl}
	mock.recorder = &MockAuthPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthPort) EXPECT() *MockAuthPortMockRecorder {
	return m.recorder
}

// AskPasswordResetMail mocks base method.
func (m *MockAuthPort) AskPasswordResetMail(email string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskPasswordResetMail", email)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// AskPasswordResetMail indicates an expected call of AskPasswordResetMail.
func (mr *MockAuthPortMockRecorder) AskPasswordResetMail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskPasswordResetMail", reflect.TypeOf((*MockAuthPort)(nil).AskPasswordResetMail), email)
}

// FindPasswordResetByToken mocks base method.
func (m *MockAuthPort) FindPasswordResetByToken(token string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPasswordResetByToken", token)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// FindPasswordResetByToken indicates an expected call of FindPasswordResetByToken.
func (mr *MockAuthPortMockRecorder) FindPasswordResetByToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPasswordResetByToken", reflect.TypeOf((*MockAuthPort)(nil).FindPasswordResetByToken), token)
}

// Login mocks base method.
func (m *MockAuthPort) Login(arg0 credentials.Credentials) (authorization.Authorization, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0)
	ret0, _ := ret[0].(authorization.Authorization)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthPortMockRecorder) Login(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthPort)(nil).Login), arg0)
}

// Logout mocks base method.
func (m *MockAuthPort) Logout(accountID *uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", accountID)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthPortMockRecorder) Logout(accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthPort)(nil).Logout), accountID)
}

// SessionExists mocks base method.
func (m *MockAuthPort) SessionExists(accountId *uuid.UUID, token string) (bool, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionExists", accountId, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// SessionExists indicates an expected call of SessionExists.
func (mr *MockAuthPortMockRecorder) SessionExists(accountId, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionExists", reflect.TypeOf((*MockAuthPort)(nil).SessionExists), accountId, token)
}

// UpdatePasswordByPasswordReset mocks base method.
func (m *MockAuthPort) UpdatePasswordByPasswordReset(token, newPassword string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordByPasswordReset", token, newPassword)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// UpdatePasswordByPasswordReset indicates an expected call of UpdatePasswordByPasswordReset.
func (mr *MockAuthPortMockRecorder) UpdatePasswordByPasswordReset(token, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordByPasswordReset", reflect.TypeOf((*MockAuthPort)(nil).UpdatePasswordByPasswordReset), token, newPassword)
}
