// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/primary/campus.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/primary/campus.go -destination=src/apps/api/handlers/mocks/campus.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	campus "eletronic_point/src/core/domain/campus"
	errors "eletronic_point/src/core/domain/errors"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCampusPort is a mock of CampusPort interface.
type MockCampusPort struct {
	ctrl     *gomock.Controller
	recorder *MockCampusPortMockRecorder
	isgomock struct{}
}

// MockCampusPortMockRecorder is the mock recorder for MockCampusPort.
type MockCampusPortMockRecorder struct {
	mock *MockCampusPort
}

// NewMockCampusPort creates a new mock instance.
func NewMockCampusPort(ctrl *gomock.Controller) *MockCampusPort {
	mock := &MockCampusPort{ctrl: ctrl}
	mock.recorder = &MockCampusPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampusPort) EXPECT() *MockCampusPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCampusPort) Create(data campus.Campus) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCampusPortMockRecorder) Create(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCampusPort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockCampusPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCampusPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCampusPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockCampusPort) Get(id uuid.UUID) (campus.Campus, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(campus.Campus)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCampusPortMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCampusPort)(nil).Get), id)
}

// List mocks base method.
func (m *MockCampusPort) List(_filters filters.CampusFilters) ([]campus.Campus, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]campus.Campus)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCampusPortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCampusPort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockCampusPort) Update(data campus.Campus) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", data)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCampusPortMockRecorder) Update(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCampusPort)(nil).Update), data)
}
