// Code generated by MockGen. DO NOT EDIT.
// Source: src/apps/api/handlers/context.go
//
// Generated by this command:
//
//	mockgen -source=src/apps/api/handlers/context.go -destination=src/apps/api/handlers/mocks/context.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	io "io"
	multipart "mime/multipart"
	http "net/http"
	url "net/url"
	reflect "reflect"

	uuid "github.com/google/uuid"
	v4 "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockRichContext is a mock of RichContext interface.
type MockRichContext struct {
	ctrl     *gomock.Controller
	recorder *MockRichContextMockRecorder
	isgomock struct{}
}

// MockRichContextMockRecorder is the mock recorder for MockRichContext.
type MockRichContextMockRecorder struct {
	mock *MockRichContext
}

// NewMockRichContext creates a new mock instance.
func NewMockRichContext(ctrl *gomock.Controller) *MockRichContext {
	mock := &MockRichContext{ctrl: ctrl}
	mock.recorder = &MockRichContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRichContext) EXPECT() *MockRichContextMockRecorder {
	return m.recorder
}

// AccountID mocks base method.
func (m *MockRichContext) AccountID() *uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountID")
	ret0, _ := ret[0].(*uuid.UUID)
	return ret0
}

// AccountID indicates an expected call of AccountID.
func (mr *MockRichContextMockRecorder) AccountID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountID", reflect.TypeOf((*MockRichContext)(nil).AccountID))
}

// Attachment mocks base method.
func (m *MockRichContext) Attachment(file, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attachment", file, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attachment indicates an expected call of Attachment.
func (mr *MockRichContextMockRecorder) Attachment(file, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attachment", reflect.TypeOf((*MockRichContext)(nil).Attachment), file, name)
}

// Bind mocks base method.
func (m *MockRichContext) Bind(i any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockRichContextMockRecorder) Bind(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockRichContext)(nil).Bind), i)
}

// Blob mocks base method.
func (m *MockRichContext) Blob(code int, contentType string, b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blob", code, contentType, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Blob indicates an expected call of Blob.
func (mr *MockRichContextMockRecorder) Blob(code, contentType, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blob", reflect.TypeOf((*MockRichContext)(nil).Blob), code, contentType, b)
}

// Cookie mocks base method.
func (m *MockRichContext) Cookie(name string) (*http.Cookie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cookie", name)
	ret0, _ := ret[0].(*http.Cookie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cookie indicates an expected call of Cookie.
func (mr *MockRichContextMockRecorder) Cookie(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookie", reflect.TypeOf((*MockRichContext)(nil).Cookie), name)
}

// Cookies mocks base method.
func (m *MockRichContext) Cookies() []*http.Cookie {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cookies")
	ret0, _ := ret[0].([]*http.Cookie)
	return ret0
}

// Cookies indicates an expected call of Cookies.
func (mr *MockRichContextMockRecorder) Cookies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookies", reflect.TypeOf((*MockRichContext)(nil).Cookies))
}

// Echo mocks base method.
func (m *MockRichContext) Echo() *v4.Echo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Echo")
	ret0, _ := ret[0].(*v4.Echo)
	return ret0
}

// Echo indicates an expected call of Echo.
func (mr *MockRichContextMockRecorder) Echo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Echo", reflect.TypeOf((*MockRichContext)(nil).Echo))
}

// Error mocks base method.
func (m *MockRichContext) Error(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", err)
}

// Error indicates an expected call of Error.
func (mr *MockRichContextMockRecorder) Error(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockRichContext)(nil).Error), err)
}

// File mocks base method.
func (m *MockRichContext) File(file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File", file)
	ret0, _ := ret[0].(error)
	return ret0
}

// File indicates an expected call of File.
func (mr *MockRichContextMockRecorder) File(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockRichContext)(nil).File), file)
}

// FormFile mocks base method.
func (m *MockRichContext) FormFile(name string) (*multipart.FileHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormFile", name)
	ret0, _ := ret[0].(*multipart.FileHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FormFile indicates an expected call of FormFile.
func (mr *MockRichContextMockRecorder) FormFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormFile", reflect.TypeOf((*MockRichContext)(nil).FormFile), name)
}

// FormParams mocks base method.
func (m *MockRichContext) FormParams() (url.Values, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormParams")
	ret0, _ := ret[0].(url.Values)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FormParams indicates an expected call of FormParams.
func (mr *MockRichContextMockRecorder) FormParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormParams", reflect.TypeOf((*MockRichContext)(nil).FormParams))
}

// FormValue mocks base method.
func (m *MockRichContext) FormValue(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormValue", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormValue indicates an expected call of FormValue.
func (mr *MockRichContextMockRecorder) FormValue(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormValue", reflect.TypeOf((*MockRichContext)(nil).FormValue), name)
}

// Get mocks base method.
func (m *MockRichContext) Get(key string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRichContextMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRichContext)(nil).Get), key)
}

// GetUUIDPathParam mocks base method.
func (m *MockRichContext) GetUUIDPathParam(key string) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUUIDPathParam", key)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetUUIDPathParam indicates an expected call of GetUUIDPathParam.
func (mr *MockRichContextMockRecorder) GetUUIDPathParam(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUUIDPathParam", reflect.TypeOf((*MockRichContext)(nil).GetUUIDPathParam), key)
}

// HTML mocks base method.
func (m *MockRichContext) HTML(code int, html string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTML", code, html)
	ret0, _ := ret[0].(error)
	return ret0
}

// HTML indicates an expected call of HTML.
func (mr *MockRichContextMockRecorder) HTML(code, html any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTML", reflect.TypeOf((*MockRichContext)(nil).HTML), code, html)
}

// HTMLBlob mocks base method.
func (m *MockRichContext) HTMLBlob(code int, b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTMLBlob", code, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// HTMLBlob indicates an expected call of HTMLBlob.
func (mr *MockRichContextMockRecorder) HTMLBlob(code, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTMLBlob", reflect.TypeOf((*MockRichContext)(nil).HTMLBlob), code, b)
}

// Handler mocks base method.
func (m *MockRichContext) Handler() v4.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler")
	ret0, _ := ret[0].(v4.HandlerFunc)
	return ret0
}

// Handler indicates an expected call of Handler.
func (mr *MockRichContextMockRecorder) Handler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockRichContext)(nil).Handler))
}

// Inline mocks base method.
func (m *MockRichContext) Inline(file, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inline", file, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Inline indicates an expected call of Inline.
func (mr *MockRichContextMockRecorder) Inline(file, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inline", reflect.TypeOf((*MockRichContext)(nil).Inline), file, name)
}

// IsAdmin mocks base method.
func (m *MockRichContext) IsAdmin() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockRichContextMockRecorder) IsAdmin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockRichContext)(nil).IsAdmin))
}

// IsTLS mocks base method.
func (m *MockRichContext) IsTLS() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTLS")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTLS indicates an expected call of IsTLS.
func (mr *MockRichContextMockRecorder) IsTLS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTLS", reflect.TypeOf((*MockRichContext)(nil).IsTLS))
}

// IsWebSocket mocks base method.
func (m *MockRichContext) IsWebSocket() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWebSocket")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWebSocket indicates an expected call of IsWebSocket.
func (mr *MockRichContextMockRecorder) IsWebSocket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWebSocket", reflect.TypeOf((*MockRichContext)(nil).IsWebSocket))
}

// JSON mocks base method.
func (m *MockRichContext) JSON(code int, i any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSON", code, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSON indicates an expected call of JSON.
func (mr *MockRichContextMockRecorder) JSON(code, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSON", reflect.TypeOf((*MockRichContext)(nil).JSON), code, i)
}

// JSONBlob mocks base method.
func (m *MockRichContext) JSONBlob(code int, b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSONBlob", code, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSONBlob indicates an expected call of JSONBlob.
func (mr *MockRichContextMockRecorder) JSONBlob(code, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSONBlob", reflect.TypeOf((*MockRichContext)(nil).JSONBlob), code, b)
}

// JSONP mocks base method.
func (m *MockRichContext) JSONP(code int, callback string, i any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSONP", code, callback, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSONP indicates an expected call of JSONP.
func (mr *MockRichContextMockRecorder) JSONP(code, callback, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSONP", reflect.TypeOf((*MockRichContext)(nil).JSONP), code, callback, i)
}

// JSONPBlob mocks base method.
func (m *MockRichContext) JSONPBlob(code int, callback string, b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSONPBlob", code, callback, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSONPBlob indicates an expected call of JSONPBlob.
func (mr *MockRichContextMockRecorder) JSONPBlob(code, callback, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSONPBlob", reflect.TypeOf((*MockRichContext)(nil).JSONPBlob), code, callback, b)
}

// JSONPretty mocks base method.
func (m *MockRichContext) JSONPretty(code int, i any, indent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSONPretty", code, i, indent)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSONPretty indicates an expected call of JSONPretty.
func (mr *MockRichContextMockRecorder) JSONPretty(code, i, indent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSONPretty", reflect.TypeOf((*MockRichContext)(nil).JSONPretty), code, i, indent)
}

// Logger mocks base method.
func (m *MockRichContext) Logger() v4.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(v4.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockRichContextMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockRichContext)(nil).Logger))
}

// MultipartForm mocks base method.
func (m *MockRichContext) MultipartForm() (*multipart.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultipartForm")
	ret0, _ := ret[0].(*multipart.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MultipartForm indicates an expected call of MultipartForm.
func (mr *MockRichContextMockRecorder) MultipartForm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultipartForm", reflect.TypeOf((*MockRichContext)(nil).MultipartForm))
}

// NoContent mocks base method.
func (m *MockRichContext) NoContent(code int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoContent", code)
	ret0, _ := ret[0].(error)
	return ret0
}

// NoContent indicates an expected call of NoContent.
func (mr *MockRichContextMockRecorder) NoContent(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoContent", reflect.TypeOf((*MockRichContext)(nil).NoContent), code)
}

// Param mocks base method.
func (m *MockRichContext) Param(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Param", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// Param indicates an expected call of Param.
func (mr *MockRichContextMockRecorder) Param(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Param", reflect.TypeOf((*MockRichContext)(nil).Param), name)
}

// ParamNames mocks base method.
func (m *MockRichContext) ParamNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParamNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ParamNames indicates an expected call of ParamNames.
func (mr *MockRichContextMockRecorder) ParamNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParamNames", reflect.TypeOf((*MockRichContext)(nil).ParamNames))
}

// ParamValues mocks base method.
func (m *MockRichContext) ParamValues() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParamValues")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ParamValues indicates an expected call of ParamValues.
func (mr *MockRichContextMockRecorder) ParamValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParamValues", reflect.TypeOf((*MockRichContext)(nil).ParamValues))
}

// Path mocks base method.
func (m *MockRichContext) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockRichContextMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockRichContext)(nil).Path))
}

// ProfileID mocks base method.
func (m *MockRichContext) ProfileID() *uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfileID")
	ret0, _ := ret[0].(*uuid.UUID)
	return ret0
}

// ProfileID indicates an expected call of ProfileID.
func (mr *MockRichContextMockRecorder) ProfileID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileID", reflect.TypeOf((*MockRichContext)(nil).ProfileID))
}

// QueryParam mocks base method.
func (m *MockRichContext) QueryParam(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryParam", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// QueryParam indicates an expected call of QueryParam.
func (mr *MockRichContextMockRecorder) QueryParam(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryParam", reflect.TypeOf((*MockRichContext)(nil).QueryParam), name)
}

// QueryParams mocks base method.
func (m *MockRichContext) QueryParams() url.Values {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryParams")
	ret0, _ := ret[0].(url.Values)
	return ret0
}

// QueryParams indicates an expected call of QueryParams.
func (mr *MockRichContextMockRecorder) QueryParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryParams", reflect.TypeOf((*MockRichContext)(nil).QueryParams))
}

// QueryString mocks base method.
func (m *MockRichContext) QueryString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryString")
	ret0, _ := ret[0].(string)
	return ret0
}

// QueryString indicates an expected call of QueryString.
func (mr *MockRichContextMockRecorder) QueryString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryString", reflect.TypeOf((*MockRichContext)(nil).QueryString))
}

// RealIP mocks base method.
func (m *MockRichContext) RealIP() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RealIP")
	ret0, _ := ret[0].(string)
	return ret0
}

// RealIP indicates an expected call of RealIP.
func (mr *MockRichContextMockRecorder) RealIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RealIP", reflect.TypeOf((*MockRichContext)(nil).RealIP))
}

// Redirect mocks base method.
func (m *MockRichContext) Redirect(code int, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redirect", code, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redirect indicates an expected call of Redirect.
func (mr *MockRichContextMockRecorder) Redirect(code, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockRichContext)(nil).Redirect), code, arg1)
}

// Render mocks base method.
func (m *MockRichContext) Render(code int, name string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", code, name, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockRichContextMockRecorder) Render(code, name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockRichContext)(nil).Render), code, name, data)
}

// Request mocks base method.
func (m *MockRichContext) Request() *http.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request")
	ret0, _ := ret[0].(*http.Request)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockRichContextMockRecorder) Request() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockRichContext)(nil).Request))
}

// Reset mocks base method.
func (m *MockRichContext) Reset(r *http.Request, w http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset", r, w)
}

// Reset indicates an expected call of Reset.
func (mr *MockRichContextMockRecorder) Reset(r, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockRichContext)(nil).Reset), r, w)
}

// Response mocks base method.
func (m *MockRichContext) Response() *v4.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response")
	ret0, _ := ret[0].(*v4.Response)
	return ret0
}

// Response indicates an expected call of Response.
func (mr *MockRichContextMockRecorder) Response() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockRichContext)(nil).Response))
}

// RoleName mocks base method.
func (m *MockRichContext) RoleName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleName")
	ret0, _ := ret[0].(string)
	return ret0
}

// RoleName indicates an expected call of RoleName.
func (mr *MockRichContextMockRecorder) RoleName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleName", reflect.TypeOf((*MockRichContext)(nil).RoleName))
}

// Scheme mocks base method.
func (m *MockRichContext) Scheme() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scheme")
	ret0, _ := ret[0].(string)
	return ret0
}

// Scheme indicates an expected call of Scheme.
func (mr *MockRichContextMockRecorder) Scheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scheme", reflect.TypeOf((*MockRichContext)(nil).Scheme))
}

// Set mocks base method.
func (m *MockRichContext) Set(key string, val any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, val)
}

// Set indicates an expected call of Set.
func (mr *MockRichContextMockRecorder) Set(key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRichContext)(nil).Set), key, val)
}

// SetCookie mocks base method.
func (m *MockRichContext) SetCookie(cookie *http.Cookie) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCookie", cookie)
}

// SetCookie indicates an expected call of SetCookie.
func (mr *MockRichContextMockRecorder) SetCookie(cookie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCookie", reflect.TypeOf((*MockRichContext)(nil).SetCookie), cookie)
}

// SetHandler mocks base method.
func (m *MockRichContext) SetHandler(h v4.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHandler", h)
}

// SetHandler indicates an expected call of SetHandler.
func (mr *MockRichContextMockRecorder) SetHandler(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHandler", reflect.TypeOf((*MockRichContext)(nil).SetHandler), h)
}

// SetLogger mocks base method.
func (m *MockRichContext) SetLogger(l v4.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", l)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockRichContextMockRecorder) SetLogger(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockRichContext)(nil).SetLogger), l)
}

// SetParamNames mocks base method.
func (m *MockRichContext) SetParamNames(names ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range names {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetParamNames", varargs...)
}

// SetParamNames indicates an expected call of SetParamNames.
func (mr *MockRichContextMockRecorder) SetParamNames(names ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParamNames", reflect.TypeOf((*MockRichContext)(nil).SetParamNames), names...)
}

// SetParamValues mocks base method.
func (m *MockRichContext) SetParamValues(values ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetParamValues", varargs...)
}

// SetParamValues indicates an expected call of SetParamValues.
func (mr *MockRichContextMockRecorder) SetParamValues(values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParamValues", reflect.TypeOf((*MockRichContext)(nil).SetParamValues), values...)
}

// SetPath mocks base method.
func (m *MockRichContext) SetPath(p string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPath", p)
}

// SetPath indicates an expected call of SetPath.
func (mr *MockRichContextMockRecorder) SetPath(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPath", reflect.TypeOf((*MockRichContext)(nil).SetPath), p)
}

// SetRequest mocks base method.
func (m *MockRichContext) SetRequest(r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequest", r)
}

// SetRequest indicates an expected call of SetRequest.
func (mr *MockRichContextMockRecorder) SetRequest(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequest", reflect.TypeOf((*MockRichContext)(nil).SetRequest), r)
}

// SetResponse mocks base method.
func (m *MockRichContext) SetResponse(r *v4.Response) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetResponse", r)
}

// SetResponse indicates an expected call of SetResponse.
func (mr *MockRichContextMockRecorder) SetResponse(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResponse", reflect.TypeOf((*MockRichContext)(nil).SetResponse), r)
}

// Stream mocks base method.
func (m *MockRichContext) Stream(code int, contentType string, r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", code, contentType, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stream indicates an expected call of Stream.
func (mr *MockRichContextMockRecorder) Stream(code, contentType, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockRichContext)(nil).Stream), code, contentType, r)
}

// String mocks base method.
func (m *MockRichContext) String(code int, s string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String", code, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockRichContextMockRecorder) String(code, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockRichContext)(nil).String), code, s)
}

// Validate mocks base method.
func (m *MockRichContext) Validate(i any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockRichContextMockRecorder) Validate(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockRichContext)(nil).Validate), i)
}

// XML mocks base method.
func (m *MockRichContext) XML(code int, i any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XML", code, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// XML indicates an expected call of XML.
func (mr *MockRichContextMockRecorder) XML(code, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XML", reflect.TypeOf((*MockRichContext)(nil).XML), code, i)
}

// XMLBlob mocks base method.
func (m *MockRichContext) XMLBlob(code int, b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XMLBlob", code, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// XMLBlob indicates an expected call of XMLBlob.
func (mr *MockRichContextMockRecorder) XMLBlob(code, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XMLBlob", reflect.TypeOf((*MockRichContext)(nil).XMLBlob), code, b)
}

// XMLPretty mocks base method.
func (m *MockRichContext) XMLPretty(code int, i any, indent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XMLPretty", code, i, indent)
	ret0, _ := ret[0].(error)
	return ret0
}

// XMLPretty indicates an expected call of XMLPretty.
func (mr *MockRichContextMockRecorder) XMLPretty(code, i, indent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XMLPretty", reflect.TypeOf((*MockRichContext)(nil).XMLPretty), code, i, indent)
}
