// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/primary/internship.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/primary/internship.go -destination=src/apps/api/handlers/mocks/internship.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	internship "eletronic_point/src/core/domain/internship"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInternshipPort is a mock of InternshipPort interface.
type MockInternshipPort struct {
	ctrl     *gomock.Controller
	recorder *MockInternshipPortMockRecorder
	isgomock struct{}
}

// MockInternshipPortMockRecorder is the mock recorder for MockInternshipPort.
type MockInternshipPortMockRecorder struct {
	mock *MockInternshipPort
}

// NewMockInternshipPort creates a new mock instance.
func NewMockInternshipPort(ctrl *gomock.Controller) *MockInternshipPort {
	mock := &MockInternshipPort{ctrl: ctrl}
	mock.recorder = &MockInternshipPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternshipPort) EXPECT() *MockInternshipPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInternshipPort) Create(arg0 internship.Internship) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInternshipPortMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInternshipPort)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockInternshipPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInternshipPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInternshipPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockInternshipPort) Get(id uuid.UUID) (internship.Internship, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(internship.Internship)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInternshipPortMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInternshipPort)(nil).Get), id)
}

// List mocks base method.
func (m *MockInternshipPort) List(_filters filters.InternshipFilters) ([]internship.Internship, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]internship.Internship)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInternshipPortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInternshipPort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockInternshipPort) Update(arg0 internship.Internship) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInternshipPortMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInternshipPort)(nil).Update), arg0)
}
