// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/primary/internshipLocation.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/primary/internshipLocation.go -destination=src/apps/api/handlers/mocks/internshipLocation.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	internshipLocation "eletronic_point/src/core/domain/internshipLocation"
	filters "eletronic_point/src/core/services/filters"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInternshipLocationPort is a mock of InternshipLocationPort interface.
type MockInternshipLocationPort struct {
	ctrl     *gomock.Controller
	recorder *MockInternshipLocationPortMockRecorder
	isgomock struct{}
}

// MockInternshipLocationPortMockRecorder is the mock recorder for MockInternshipLocationPort.
type MockInternshipLocationPortMockRecorder struct {
	mock *MockInternshipLocationPort
}

// NewMockInternshipLocationPort creates a new mock instance.
func NewMockInternshipLocationPort(ctrl *gomock.Controller) *MockInternshipLocationPort {
	mock := &MockInternshipLocationPort{ctrl: ctrl}
	mock.recorder = &MockInternshipLocationPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternshipLocationPort) EXPECT() *MockInternshipLocationPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInternshipLocationPort) Create(arg0 internshipLocation.InternshipLocation) (*uuid.UUID, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInternshipLocationPortMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInternshipLocationPort)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockInternshipLocationPort) Delete(id uuid.UUID) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInternshipLocationPortMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInternshipLocationPort)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockInternshipLocationPort) Get(id uuid.UUID) (internshipLocation.InternshipLocation, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(internshipLocation.InternshipLocation)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInternshipLocationPortMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInternshipLocationPort)(nil).Get), id)
}

// List mocks base method.
func (m *MockInternshipLocationPort) List(_filters filters.InternshipLocationFilters) ([]internshipLocation.InternshipLocation, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", _filters)
	ret0, _ := ret[0].([]internshipLocation.InternshipLocation)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInternshipLocationPortMockRecorder) List(_filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInternshipLocationPort)(nil).List), _filters)
}

// Update mocks base method.
func (m *MockInternshipLocationPort) Update(arg0 internshipLocation.InternshipLocation) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInternshipLocationPortMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInternshipLocationPort)(nil).Update), arg0)
}
