// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/interfaces/primary/resources.go
//
// Generated by this command:
//
//	mockgen -source=src/core/interfaces/primary/resources.go -destination=src/apps/api/handlers/mocks/resources.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "eletronic_point/src/core/domain/errors"
	role "eletronic_point/src/core/domain/role"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResourcesPort is a mock of ResourcesPort interface.
type MockResourcesPort struct {
	ctrl     *gomock.Controller
	recorder *MockResourcesPortMockRecorder
	isgomock struct{}
}

// MockResourcesPortMockRecorder is the mock recorder for MockResourcesPort.
type MockResourcesPortMockRecorder struct {
	mock *MockResourcesPort
}

// NewMockResourcesPort creates a new mock instance.
func NewMockResourcesPort(ctrl *gomock.Controller) *MockResourcesPort {
	mock := &MockResourcesPort{ctrl: ctrl}
	mock.recorder = &MockResourcesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcesPort) EXPECT() *MockResourcesPortMockRecorder {
	return m.recorder
}

// ListAccountRoles mocks base method.
func (m *MockResourcesPort) ListAccountRoles() ([]role.Role, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountRoles")
	ret0, _ := ret[0].([]role.Role)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ListAccountRoles indicates an expected call of ListAccountRoles.
func (mr *MockResourcesPortMockRecorder) ListAccountRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountRoles", reflect.TypeOf((*MockResourcesPort)(nil).ListAccountRoles))
}
