basePath: /api
definitions:
  request.CreateAccount:
    properties:
      birth_date:
        type: string
      cpf:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      role_code:
        type: string
    type: object
  request.CreatePasswordReset:
    properties:
      email:
        type: string
    type: object
  request.Credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.Student:
    properties:
      course:
        type: string
      institution:
        type: string
      internship_address:
        type: string
      internship_location:
        type: string
      internship_location_name:
        type: string
      name:
        type: string
      profile_picture:
        type: string
      registration:
        type: string
      total_workload:
        type: integer
    type: object
  request.UpdateAccountProfile:
    properties:
      birth_date:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  request.UpdatePassword:
    properties:
      current_password:
        type: string
      new_password:
        type: string
    type: object
  request.UpdatePasswordByPasswordReset:
    properties:
      new_password:
        type: string
    type: object
  response.Account:
    properties:
      email:
        type: string
      id:
        type: string
      professional:
        $ref: '#/definitions/response.Professional'
      profile:
        $ref: '#/definitions/response.Person'
      role:
        $ref: '#/definitions/response.Role'
    type: object
  response.Authorization:
    properties:
      access_token:
        type: string
    type: object
  response.ErrorMessage:
    properties:
      error: {}
      invalid_fields:
        items:
          $ref: '#/definitions/response.InvalidField'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  response.ID:
    properties:
      id:
        type: string
    type: object
  response.InvalidField:
    properties:
      description:
        type: string
      field_name:
        type: string
    type: object
  response.Person:
    properties:
      birth_date:
        type: string
      cpf:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  response.Professional:
    properties:
      id:
        type: string
    type: object
  response.Role:
    properties:
      code:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  response.Student:
    properties:
      course:
        type: string
      frequency_history:
        type: string
      id:
        type: string
      institution:
        type: string
      internship_address:
        type: string
      internship_location:
        type: string
      internship_location_name:
        type: string
      name:
        type: string
      pending_workload:
        type: integer
      profile_picture:
        type: string
      registration:
        type: string
      total_workload:
        type: integer
      workload_completed:
        type: integer
    type: object
info:
  contact:
    email: wmrn1@aluno.ifal.edu.br
    name: DIT - IFAL
  description: DIT Backend template for new backend projects
  title: DIT Backend API
  version: "1.0"
paths:
  /accounts/profile:
    get:
      description: |-
        Esta rota retorna todas as informações de todas as contas cadastradas no banco de dados.
        Dados como "professional" irão somente aparecer caso a role da conta for própria para contenção desses.
      operationId: Accounts.FindProfile
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.Account'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Pesquisar dados do perfil de uma conta.
      tags:
      - Geral
    put:
      consumes:
      - application/json
      operationId: Account.UpdateProfile
      parameters:
      - description: JSON com todos os dados necessários para o processo de atualização
          de dados do perfil.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.UpdateAccountProfile'
      responses:
        "200":
          description: OK
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Atualizar dados do perfil de uma conta.
      tags:
      - Geral
  /accounts/update-password:
    put:
      consumes:
      - application/json
      operationId: Account.UpdateAccountPassword
      parameters:
      - description: JSON com todos os dados necessários para a atualização da senha
          da conta.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePassword'
      responses:
        "200":
          description: OK
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Realizar a atualização de senha de uma conta.
      tags:
      - Geral
  /admin/accounts:
    get:
      description: |-
        Esta rota retorna todas as informações de todas as contas cadastradas no banco de dados.
        Dados como "professional" irão somente aparecer caso a role da conta for própria para contenção desses.
      operationId: Accounts.List
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.Account'
            type: array
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Listar todas as contas existentes do banco de dados.
      tags:
      - Administrador
    post:
      consumes:
      - application/json
      description: |-
        Ao enviar dados para cadastro de uma nova conta, os dados relacionados à "Profissional"
        são facultativos, tendo somente que enviar os dados que são relacionados à role definida.
      operationId: Accounts.Create
      parameters:
      - description: JSON com todos os dados necessários para o cadastro de uma conta
          de usuário.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccount'
      produces:
      - application/json
      responses:
        "201":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.ID'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Cadastrar uma nova conta de usuário
      tags:
      - Administrador
  /auth/login:
    post:
      consumes:
      - application/json
      operationId: Auth.Login
      parameters:
      - description: JSON com todos os dados necessários para o processo de autenticação.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.Authorization'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Adquirir autorização de acesso aos recursos da API através de credenciais
        de uma conta.
      tags:
      - Anônimo
  /auth/logout:
    post:
      operationId: Auth.Logout
      produces:
      - application/json
      responses:
        "204":
          description: Requisição realizada com sucesso.
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Remove a sessão do registro de sessões permitidas.
      tags:
      - Geral
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: |-
        cadastra uma nova entrada para a entidade `password_reset` vinculada à conta da sessão
        e envia um e-mail para o email dessa.
      operationId: Auth.PasswordReset
      parameters:
      - description: JSON com todos os dados necessários para resetar a senha por
          email.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.CreatePasswordReset'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Solicitar email com token para atualização de senha.
      tags:
      - Anônimo
  /auth/reset-password/{token}:
    get:
      consumes:
      - application/json
      operationId: Auth.FindPasswordResetByToken
      parameters:
      - description: Token recebido pelo email da conta do usuário da plataforma.
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Verificar a existência de uma solicitação de atualização de senha por
        token.
      tags:
      - Anônimo
    put:
      consumes:
      - application/json
      operationId: Auth.UpdatePasswordByPasswordReset
      parameters:
      - description: Token recebido pelo email da conta do usuário da plataforma.
        in: path
        name: token
        required: true
        type: string
      - description: JSON com todos os dados necessários para resetar a senha por
          email.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePasswordByPasswordReset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Atualizar a senha de uma conta a partir de um token de atualização
        de senha.
      tags:
      - Anônimo
  /res/account-roles:
    get:
      description: |-
        Pode ser utilizada para visualizar as funções de conta cadastradas no banco de dados e adquirir o
        identificador da função desejada para a criação de uma nova conta.
      operationId: Resources.ListAccountRoles
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.Role'
            type: array
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Listar todas as funções de conta existentes do banco de dados.
      tags:
      - Recursos
  /students:
    get:
      description: Recupera todos os estudantes registrados no sistema.
      operationId: Student.List
      produces:
      - application/json
      responses:
        "200":
          description: Lista de estudantes.
          schema:
            items:
              $ref: '#/definitions/response.Student'
            type: array
        "500":
          description: Erro inesperado. Por favor, entre em contato com o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Listar todos os estudantes.
      tags:
      - Estudantes
    post:
      consumes:
      - application/json
      description: Cria um novo estudante no sistema com os dados fornecidos.
      operationId: Student.Create
      parameters:
      - description: Dados do estudante
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/request.Student'
      produces:
      - application/json
      responses:
        "201":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.ID'
        "400":
          description: Requisição mal formulada.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "401":
          description: Usuário não autorizado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "403":
          description: Acesso negado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "404":
          description: Recurso não encontrado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "409":
          description: A solicitação não pôde ser concluída devido a um conflito com
            o estado atual do recurso de destino.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "422":
          description: Ocorreu um erro de validação de dados. Vefique os valores,
            tipos e formatos de dados enviados.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Criar um novo estudante.
      tags:
      - Estudantes
  /students/{id}:
    delete:
      description: Remove um estudante do sistema.
      operationId: Student.Delete
      parameters:
      - description: ID do estudante
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Estudante removido com sucesso.
        "404":
          description: Estudante não encontrado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Erro inesperado. Por favor, entre em contato com o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Deletar um estudante.
      tags:
      - Estudantes
    get:
      description: Recupera os dados de um estudante específico pelo seu ID.
      operationId: Student.Get
      parameters:
      - description: ID do estudante
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Estudante encontrado.
          schema:
            $ref: '#/definitions/response.Student'
        "404":
          description: Estudante não encontrado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Erro inesperado. Por favor, entre em contato com o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Obter um estudante por ID.
      tags:
      - Estudantes
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um estudante existente no sistema.
      operationId: Student.Update
      parameters:
      - description: ID do estudante
        in: path
        name: id
        required: true
        type: string
      - description: Dados do estudante
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/request.Student'
      produces:
      - application/json
      responses:
        "200":
          description: Estudante atualizado com sucesso.
          schema:
            $ref: '#/definitions/response.Student'
        "400":
          description: Dados inválidos fornecidos.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "404":
          description: Estudante não encontrado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Erro inesperado. Por favor, entre em contato com o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      security:
      - bearerAuth: []
      summary: Atualizar informações de um estudante.
      tags:
      - Estudantes
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
